name: CI

on:
  push:
    branches: [ master, develop ]
    tags-ignore:
      - 'v*'
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install ninja-build and cmake
      run: |
          sudo apt install ninja-build cmake

    - name: Install clang-9 and gcc-9
      run: |
          sudo apt install -y clang-9 clang-format-9 clang-tidy-9 gcc-9 g++-9

    - name: Build project
      run: |
          mkdir build && cd build
          export CC=clang-9
          export CXX=clang++-9
          cmake \
            -G"Ninja" \
            -DENABLE_SANITIZER_ADDRESS=ON \
            -DENABLE_SANITIZER_UNDEFINED=ON \
            ..
          mv compile_commands.json ..
          cmake --build .

    - name: Run tests
      run: |
          cd build
          ctest -V
